import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/NavBar";
import Footer from "@/Components/Footer";

const outfitFont = Outfit({
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${outfitFont.className} h-full antialiased`}
    >
      <body className="">
        <Navbar></Navbar>
        <main>
        {children}
        </main>
        <Footer></Footer>
      </body>
    </html>
  );
}
